version: '2'
services:

  # ports -> HOST:CONTAINER

  postgres:
    image: postgres:13-alpine
    restart: always
    ports:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  hub-api:
    build: ./hub-api
    restart: on-failure
    ports:
      - "8080"


volumes:
  postgres_data:
